modLoader = "javafml"
loaderVersion = "[32,)"
issueTrackerURL = ""
license = "GNU LGPLv3"

[[mods]]
modId = "probejs"
version = "${version}"
displayName = "ProbeJS"
authors = "Prunoideae & ZZZank"
description = '''
KubeJS data dumper
'''
license = "GNU LGPLv3"

[[dependencies.probejs]]
modId = "kubejs"
mandatory = true
versionRange = "[1605.3.19-build.299,)"
ordering = "AFTER"
side = "BOTH"
